---
title: "Engineering"
description: "Joy hidden in a mess"
date: 2025-12-06
categories: [General]
---

Engineering is one of humanity’s greatest assets. From landing on Mars to exploring the Mariana Trench, none of it would be possible without the mind of engineers. While scientists try to understand why the world behaves a certain way, engineers use those principles to solve real problems, and that journey isn't always pleasant.

In fact, whatever you think _might_ go wrong usually _goes_ wrong. Yet when engineering action works, it gives a great sense of joy.

The process starts with a simple proof of concept, just to note what works and what fails. Through countless iterations, trial and error, and messy experiments, engineers reach closer to a solution. Failure isn’t just expected; it’s a natural and important part of the process. As Thomas Edison famously said, _“I have not failed. I've just found 10,000 ways that won’t work.”_

Instead of tackling a problem all at once, engineers break it into manageable steps, ask hard questions, think critically, and stay curious. When something breaks—and it will—they reflect on why. After failing repeatedly, anyone might feel stupid. But there’s nothing wrong with that feeling. It simply means you are learning. In the end, resilience is what makes repeated failures into success. And that transformation is what makes engineering so deeply rewarding.

And the best part is, you don’t need a college degree to become an engineer. If you’re curious enough, ask hard questions, and learn specific set of skills which you can apply to solve set of problems, you’re already thinking like an engineer. As George Bernard Shaw put it, _“Life isn’t about finding yourself. Life is about creating yourself.”_ With curiosity, resilience, and a little bit of luck, you can create yourself into an engineer.

---
